export const demoUsers = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    role: "Admin",
    address: "123 Main St, Cityville",
    phone: "123-456-7890",
    status: "Active",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    role: "User",
    address: "456 Oak St, Townsville",
    phone: "234-567-8901",
    status: "Inactive",
  },
  {
    id: 3,
    name: "Mark Taylor",
    email: "mark@example.com",
    role: "Owner",
    address: "789 Pine St, Villagetown",
    phone: "345-678-9012",
    status: "Active",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily@example.com",
    role: "User",
    address: "321 Birch St, Hamlet",
    phone: "456-789-0123",
    status: "Active",
  },
  {
    id: 5,
    name: "Chris Brown",
    email: "chris@example.com",
    role: "Admin",
    address: "654 Cedar St, Cityville",
    phone: "567-890-1234",
    status: "Inactive",
  },
  {
    id: 6,
    name: "Anna Wilson",
    email: "anna@example.com",
    role: "Owner",
    address: "987 Maple St, Townsville",
    phone: "678-901-2345",
    status: "Active",
  },
  {
    id: 7,
    name: "Paul White",
    email: "paul@example.com",
    role: "User",
    address: "123 Oak St, Villagetown",
    phone: "789-012-3456",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Lucy Green",
    email: "lucy@example.com",
    role: "Admin",
    address: "234 Pine St, Hamlet",
    phone: "890-123-4567",
    status: "Active",
  },
  {
    id: 9,
    name: "Sophia Black",
    email: "sophia@example.com",
    role: "User",
    address: "345 Birch St, Cityville",
    phone: "901-234-5678",
    status: "Active",
  },
  {
    id: 10,
    name: "James Martin",
    email: "james@example.com",
    role: "Owner",
    address: "456 Cedar St, Townsville",
    phone: "012-345-6789",
    status: "Inactive",
  },
  {
    id: 11,
    name: "Olivia Johnson",
    email: "olivia@example.com",
    role: "User",
    address: "567 Maple St, Villagetown",
    phone: "123-456-7890",
    status: "Active",
  },
  {
    id: 12,
    name: "David Lee",
    email: "david@example.com",
    role: "Admin",
    address: "678 Oak St, Hamlet",
    phone: "234-567-8901",
    status: "Inactive",
  },
  {
    id: 13,
    name: "Emma Clark",
    email: "emma@example.com",
    role: "Owner",
    address: "789 Pine St, Cityville",
    phone: "345-678-9012",
    status: "Active",
  },
  {
    id: 14,
    name: "William Harris",
    email: "william@example.com",
    role: "User",
    address: "890 Birch St, Townsville",
    phone: "456-789-0123",
    status: "Active",
  },
  {
    id: 15,
    name: "Isabella Lewis",
    email: "isabella@example.com",
    role: "Admin",
    address: "123 Cedar St, Villagetown",
    phone: "567-890-1234",
    status: "Inactive",
  },
  {
    id: 16,
    name: "Benjamin Walker",
    email: "benjamin@example.com",
    role: "User",
    address: "234 Maple St, Hamlet",
    phone: "678-901-2345",
    status: "Active",
  },
  {
    id: 17,
    name: "Charlotte Young",
    email: "charlotte@example.com",
    role: "Owner",
    address: "345 Oak St, Cityville",
    phone: "789-012-3456",
    status: "Inactive",
  },
  {
    id: 18,
    name: "Alexander King",
    email: "alexander@example.com",
    role: "Admin",
    address: "456 Pine St, Townsville",
    phone: "890-123-4567",
    status: "Active",
  },
  {
    id: 19,
    name: "Mia Wright",
    email: "mia@example.com",
    role: "User",
    address: "567 Birch St, Villagetown",
    phone: "901-234-5678",
    status: "Inactive",
  },
  {
    id: 20,
    name: "Ethan Scott",
    email: "ethan@example.com",
    role: "Owner",
    address: "678 Cedar St, Hamlet",
    phone: "012-345-6789",
    status: "Active",
  },
  {
    id: 21,
    name: "Ava Allen",
    email: "ava@example.com",
    role: "User",
    address: "789 Maple St, Cityville",
    phone: "123-456-7890",
    status: "Active",
  },
  {
    id: 22,
    name: "Daniel Adams",
    email: "daniel@example.com",
    role: "Admin",
    address: "890 Oak St, Townsville",
    phone: "234-567-8901",
    status: "Inactive",
  },
  {
    id: 23,
    name: "Grace Thompson",
    email: "grace@example.com",
    role: "User",
    address: "123 Birch St, Villagetown",
    phone: "345-678-9012",
    status: "Active",
  },
  {
    id: 24,
    name: "Henry White",
    email: "henry@example.com",
    role: "Owner",
    address: "234 Pine St, Hamlet",
    phone: "456-789-0123",
    status: "Inactive",
  },
  {
    id: 25,
    name: "Amelia Moore",
    email: "amelia@example.com",
    role: "Admin",
    address: "345 Cedar St, Cityville",
    phone: "567-890-1234",
    status: "Active",
  },
  {
    id: 26,
    name: "Jack Martinez",
    email: "jack@example.com",
    role: "User",
    address: "456 Maple St, Townsville",
    phone: "678-901-2345",
    status: "Inactive",
  },
  {
    id: 27,
    name: "Lily Jackson",
    email: "lily@example.com",
    role: "Owner",
    address: "567 Oak St, Villagetown",
    phone: "789-012-3456",
    status: "Active",
  },
  {
    id: 28,
    name: "Noah Perez",
    email: "noah@example.com",
    role: "User",
    address: "678 Birch St, Hamlet",
    phone: "890-123-4567",
    status: "Inactive",
  },
  {
    id: 29,
    name: "Lucas Thomas",
    email: "lucas@example.com",
    role: "Admin",
    address: "789 Cedar St, Cityville",
    phone: "901-234-5678",
    status: "Active",
  },
  {
    id: 30,
    name: "Chloe Robinson",
    email: "chloe@example.com",
    role: "User",
    address: "890 Maple St, Townsville",
    phone: "012-345-6789",
    status: "Inactive",
  },
];
